### ISSUE TITLE
Invalid bounds causes java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by dabd** [scalatest/scalatest#1126]
The following test triggers the mentioned error when the list `xs` is empty, creating in invalid bound for `Gen.choose`:

```scala
 "test" should "be" in {
    val g =
      for {
        xs <- Gen.listOf(Arbitrary.arbInt.arbitrary)
        n <- Gen.choose(0, xs.length - 1)
      } yield (xs, n)
    forAll(g) {
      case (_, _) => true mustBe true
    }
  }
```

**Comment by morgen-peschke** [comment]
This looks like it may have been fixed in 3.02

https://github.com/scalatest/scalatest/issues/992

**Comment by brandon-leapyear** [comment]
I'm still seeing this, using
```scala
val scala = "2.11.12"
val scalaCheck = "org.scalacheck" %% "scalacheck" % "1.14.0"
val scalaTest = "org.scalatest" %% "scalatest" % "3.2.2"
val scalaTestScalaCheck = "org.scalatestplus" %% "scalacheck-1-15" % "3.2.3.0"
```
The original post fails for me with `Malformed class name`, as does using nested forAlls
```scala
forAll(Gen.choose(0, 1)) { _ =>
  forAll(Gen.choose(1, 0)) { _ < 10 }
}
```
It's fine for a single forAll:
```scala
// org.scalacheck.Gen$Choose$IllegalBoundsError: invalid bounds: low=1, high=0
forAll(Gen.choose(1, 0)) { _ < 10 }
```
