### ISSUE TITLE
Incorrect failure message in assertion -- macro issue?

### ISSUE THREAD

**Issue by charpov** [scalatest/scalatest#2087]
I have an assertion of the form:
```scala
import scala.math.Ordering.Implicits.infixOrderingOps
...
assert(first <= second, ": out of order")
```
When values are out of order, the following message is produced:
```
scala.math.Ordering$OrderingOps@67fa301e was not less than or equal to 33819 : out of order
```
(In that test, the type of `first` and `second` was `java.lang.Integer`.)

If needed, I can try and extract a self-contained reproducible test.

I'm using Scala 3.1.0 and Scalatest 3.2.10.

**Comment by cheeseng** [comment]
@charpov Interesting, I think the 'first' is wrapped as OrderingOps automatically by the compiler to get the <= function, I'll look into the macro to see if I can fix this.

**Comment by cheeseng** [comment]
@charpov Finding so far suggest that this only happens in Scala 3.x, and when import scala.math.Ordering.Implicits.infixOrderingOps .

**Comment by cheeseng** [comment]
@charpov fyi I just submitted the following PR for this: 

https://github.com/scalatest/scalatest/pull/2089

**Comment by cheeseng** [comment]
@charpov fyi this should be fixed now in 3.2.11, do you mind to verify and close this ticket if it works?

Thanks.

**Comment by charpov** [comment]
For some reason, it still doesn't work for me.  I've updated my testing library to 3.2.11, and created a simple test (https://github.com/charpov/TestInOrder).  The assertion message is still off.

It does work when I use `assert` directly, so maybe my `assertInOrder` method is doing something wrong, like somehow using a different `assert`?

```scala
import org.scalactic.{ Prettifier, source }
import org.scalatest.Assertions.assert
import org.scalatest.{ Assertion, Succeeded }

import scala.annotation.tailrec
import scala.math.Ordering.Implicits.infixOrderingOps

@tailrec
def assertInOrder[A : Ordering](list: List[A])(using Prettifier, source.Position): Assertion =
   list match
      case first :: (more @ second :: _) =>
         assert(first <= second, ": out of order")
         assertInOrder(more)
      case _ => Succeeded
```

**Comment by cheeseng** [comment]
@charpov Thanks for the repo to reproduce the problem, I'll try to see what's still missing.

**Comment by cheeseng** [comment]
@charpov Fyi I have submitted a new PR to address this issue: 

https://github.com/scalatest/scalatest/pull/2107

I'll try to see if we can release a 3.2.12-RC2 that includes the fix so that you can test it out and see if it fixes all your cases.

Thanks.

**Comment by cheeseng** [comment]
@charpov Version 3.2.12-RC2 is up, do you mind to verify again if it fixes your issue?

Thanks.

**Comment by charpov** [comment]
Everything works fine with 3.2.12-RC2.

**Comment by cheeseng** [comment]
@charpov Thanks for your help to verify!  We'll include the fix in the upcoming 3.2.12.

**Comment by charpov** [comment]
While this is fresh in your mind, it looks like:
```scala
assert(list.lengthIs < 21)
```

produce a message of the form:
```
scala.collection.IterableOps$SizeCompareOps@b7bedacf was not less than 21
```
